### ISSUE TITLE
Configure NTP on EKS nodes at startup

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/delivery-nutanix-iac#23]

**Comment by jacobbmay** [comment]
Looking in eks anywhere docs, this might not be possible to configure with eks anywhere currently for nutanix. Anywhere seems to only support OS level configuration, where they put NTP configuration, for vsphere. Needs more investigation or will have to be configured via DHCP.

**Comment by JoeHCQ1** [comment]
Re-opening per discussion w/ Jacob - though I suspect we should close this if we are not doing EKS-D anymore.

**Comment by jacobbmay** [comment]
EKS-D work is OBE and no longer going to be supported

**Comment by JoeHCQ1** [comment]
Added wontfix label and unassigned individuals so it's clearly done as in canceled, not done as in performed.
